import json, sys
sys.path.append(r'C:\Users\YUSUF\.gemini\antigravity\scratch')
from story_analyzer import generate_story

match = {
    "ev_sahibi": "Kapa",
    "deplasman": "FC KTP",
    "tarih": "2026-06-04",
    "lig": "",
    "oranlar": {
        "Maç Sonucu_1": 4.34,
        "Maç Sonucu_0": 3.53,
        "Maç Sonucu_2": 1.47,
        "Çifte Şans_1 ve 0": 1.86,
        "Çifte Şans_1 ve 2": 1.11,
        "Çifte Şans_0 ve 2": 1.06,
        "Alt/Üst 1.5_Alt": 3.82,
        "Alt/Üst 1.5_Üst": 1.07,
        "Alt/Üst 2.5_Alt": 1.93,
        "Alt/Üst 2.5_Üst": 1.47,
        "Alt/Üst 3.5_Alt": 1.31,
        "Alt/Üst 3.5_Üst": 2.32,
        "Karşılıklı Gol_Var": 1.51,
        "Karşılıklı Gol_Yok": 1.88,
        "İlk Yarı Sonucu_1": 4.58,
        "İlk Yarı Sonucu_0": 2.21,
        "İlk Yarı Sonucu_2": 1.92,
        "İlk Yarı Alt/Üst 0.5_Alt": 3.01,
        "İlk Yarı Alt/Üst 0.5_Üst": 1.16,
        "İlk Yarı Alt/Üst 1.5_Alt": 1.38,
        "İlk Yarı Alt/Üst 1.5_Üst": 2.12,
        "İlk Yarı Karşılıklı Gol_Var": 3.6,
        "İlk Yarı Karşılıklı Gol_Yok": 1.09,
        "İkinci Yarı Karşılıklı Gol_Var": 2.84,
        "İkinci Yarı Karşılıklı Gol_Yok": 1.19,
        "Ev Sahibi Alt/Üst 0.5_Alt": 2.31,
        "Ev Sahibi Alt/Üst 0.5_Üst": 1.31,
        "Ev Sahibi Alt/Üst 1.5_Alt": 1.18,
        "Ev Sahibi Alt/Üst 1.5_Üst": 2.88,
        "Deplasman Alt/Üst 0.5_Alt": 5.05,
        "Deplasman Alt/Üst 1.5_Alt": 1.97,
        "Deplasman Alt/Üst 1.5_Üst": 1.46,
        "Ev Sahibi İlk Yarı Altı/Üstü 0.5_Alt": 1.33,
        "Ev Sahibi İlk Yarı Altı/Üstü 0.5_Üst": 2.25,
        "Deplasman İlk Yarı Altı/Üstü 0.5_Alt": 2.01,
        "Deplasman İlk Yarı Altı/Üstü 0.5_Üst": 1.44,
        "Her İki Yarıda da Alt 1.5_Evet": 2.57,
        "Her İki Yarıda da Alt 1.5_Hayır": 1.24,
        "Her İki Yarıda da Üst 1.5_Evet": 3.94,
        "Her İki Yarıda da Üst 1.5_Hayır": 1.07,
        "Hangi Yarıda Daha Fazla Gol Olur_1.": 2.73,
        "Hangi Yarıda Daha Fazla Gol Olur_Eşit": 3.31,
        "Hangi Yarıda Daha Fazla Gol Olur_2.": 1.9,
        "Toplam Gol_0-1 gol": 3.99,
        "Toplam Gol_2-3 gol": 1.85,
        "Toplam Gol_4-5 gol": 3.01,
        "Toplam Gol_6+ gol": 9.36,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_1 ve Alt": 6.7,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_0 ve Alt": 3.06,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_2 ve Alt": 3.48,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_1 ve Üst": 12.8,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_0 ve Üst": 6.8,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_2 ve Üst": 3.82
    }
}

print(generate_story(match))
