import json
from story_analyzer import generate_story

match_data = {
      "ev_sahibi": "FK Kosice",
      "deplasman": "AS Trencin",

      "oranlar": {
        "Maç Sonucu_1": 1.51,
        "Maç Sonucu_0": 3.61,
        "Maç Sonucu_2": 3.92,
        "Handikaplı Maç Sonucu 0:1_1": 2.33,
        "Handikaplı Maç Sonucu 0:1_0": 3.54,
        "Handikaplı Maç Sonucu 0:1_2": 1.85,
        "Maç Sonucu ve Alt/Üst 1.5_1 ve Alt": 10.05,
        "Maç Sonucu ve Alt/Üst 1.5_0 ve Alt": 17.45,
        "Maç Sonucu ve Alt/Üst 1.5_2 ve Alt": 17.35,
        "Maç Sonucu ve Alt/Üst 1.5_1 ve Üst": 1.7,
        "Maç Sonucu ve Alt/Üst 1.5_0 ve Üst": 4.22,
        "Maç Sonucu ve Alt/Üst 1.5_2 ve Üst": 4.76,
        "Çifte Şans_1 ve 0": 1.07,
        "Çifte Şans_1 ve 2": 1.1,
        "Çifte Şans_0 ve 2": 1.81,
        "1. Yarı Sonucu_1": 1.93,
        "1. Yarı Sonucu_0": 2.3,
        "1. Yarı Sonucu_2": 4.14,
        "2. Yarı Sonucu_1": 1.83,
        "2. Yarı Sonucu_0": 2.64,
        "2. Yarı Sonucu_2": 3.73,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_1 ve Var": 9.76,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_1 ve Yok": 2.29,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_0 ve Var": 6.13,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_0 ve Yok": 3.38,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_2 ve Var": 19.9,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_2 ve Yok": 4.94,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_1 ve Alt": 3.73,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_0 ve Alt": 3.4,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_2 ve Alt": 6.52,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_1 ve Üst": 3.63,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_0 ve Üst": 6.18,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_2 ve Üst": 10.15,
        "1. Yarı Karşılıklı Gol_Var": 3.19,
        "1. Yarı Karşılıklı Gol_Yok": 1.14,
        "1. Yarı Çifte Şans_1 ve 0": 1.07,
        "1. Yarı Çifte Şans_1 ve 2": 1.3,
        "1. Yarı Çifte Şans_0 ve 2": 1.46,
        "1. Yarı Tek/Çift_Tek": 1.78,
        "1. Yarı Tek/Çift_Çift": 1.59,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Alt ve Var": 7.7,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Üst ve Var": 1.62,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Alt ve Yok": 2.97,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Üst ve Yok": 6.78,
        "Maç Sonucu ve Karşılıklı Gol_1 ve Var": 2.66,
        "Maç Sonucu ve Karşılıklı Gol_1 ve Yok": 3.12,
        "Maç Sonucu ve Karşılıklı Gol_0 ve Var": 4.29,
        "Maç Sonucu ve Karşılıklı Gol_0 ve Yok": 17.75,
        "Maç Sonucu ve Karşılıklı Gol_2 ve Var": 6.39,
        "Maç Sonucu ve Karşılıklı Gol_2 ve Yok": 9.23,
        "Alt/Üst 2.5_Alt": 2.2,
        "Alt/Üst 2.5_Üst": 1.35,
        "Alt/Üst 3.5_Alt": 1.44,
        "Alt/Üst 3.5_Üst": 2.01,
        "Alt/Üst 4.5_Alt": 1.11,
        "Alt/Üst 4.5_Üst": 3.42,
        "Ev Sahibi Alt/Üst 1.5_Alt": 2.09,
        "Ev Sahibi Alt/Üst 1.5_Üst": 1.39,
        "Deplasman Alt/Üst 1.5_Alt": 1.28,
        "Deplasman Alt/Üst 1.5_Üst": 2.42,
        "Her İki Yarıda da Alt 1.5_Evet": 2.96,
        "Her İki Yarıda da Alt 1.5_Hayır": 1.17,
        "Her İki Yarıda da Üst 1.5_Evet": 3.35,
        "Her İki Yarıda da Üst 1.5_Hayır": 1.12,
        "1. Yarı Alt/Üst 1.5_Alt": 1.47,
        "1. Yarı Alt/Üst 1.5_Üst": 1.94,
        "Ev Sahibi 1. Yarı Altı/Üstü 0.5_Alt": 2.08,
        "Ev Sahibi 1. Yarı Altı/Üstü 0.5_Üst": 1.4,
        "Deplasman 1. Yarı Altı/Üstü 0.5_Alt": 1.43,
        "Deplasman 1. Yarı Altı/Üstü 0.5_Üst": 2.02,
        "Karşılıklı Gol_Var": 1.38,
        "Karşılıklı Gol_Yok": 2.13,
        "Toplam Gol_0-1 gol": 4.85,
        "Toplam Gol_2-3 gol": 1.95,
        "Toplam Gol_4-5 gol": 2.72,
        "Toplam Gol_6+ gol": 7.03,
        "Hangi Yarıda Daha Fazla Gol Olur_1.": 2.72,
        "Hangi Yarıda Daha Fazla Gol Olur_Eşit": 3.47,
        "Hangi Yarıda Daha Fazla Gol Olur_2.": 1.85,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_1.": 2.76,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_Eşit": 2.78,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_2.": 2.11,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_1.": 3.36,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_Eşit": 2.02,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_2.": 2.49,
        "Tek / Çift_Tek": 1.72,
        "Tek / Çift_Çift": 1.63,
        "2. Yarı Karşılıklı Gol_Var": 2.49,
        "2. Yarı Karşılıklı Gol_Yok": 1.26,
        "Ev Sahibi Her İki Yarıda da Gol Atar_Evet": 2.04,
        "Ev Sahibi Her İki Yarıda da Gol Atar_Hayır": 1.42,
        "Deplasman Her İki Yarıda da Gol Atar_Evet": 3.89,
        "Deplasman Her İki Yarıda da Gol Atar_Hayır": 1.07,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Hayır / Hayır": 1.64,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Evet / Hayır": 4.74,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Evet / Evet": 9.81,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Hayır / Evet": 3.28
    }
}

story = generate_story(match_data, verbose=False)
print(story)
