import json, sys
sys.path.append(r'C:\Users\YUSUF\.gemini\antigravity\scratch')
from story_analyzer import generate_story

match = {
    "ev_sahibi": "Türkiye",
    "deplasman": "Paraguay",
    "tarih": "2026-06-03",
    "lig": "",
    "skor_ev": 0,
    "skor_dep": 1,
    "skor_1y_ev": 0,
    "skor_1y_dep": 1,
    "oranlar": {
        "Maç Sonucu_1": 2.01,
        "Maç Sonucu_0": 2.9,
        "Maç Sonucu_2": 3.12,
        "Çifte Şans_1 ve 0": 1.19,
        "Çifte Şans_1 ve 2": 1.23,
        "Çifte Şans_0 ve 2": 1.49,
        "Alt/Üst 1.5_Alt": 2.63,
        "Alt/Üst 1.5_Üst": 1.29,
        "Alt/Üst 2.5_Alt": 1.46,
        "Alt/Üst 2.5_Üst": 2.09,
        "Alt/Üst 3.5_Alt": 1.1,
        "Alt/Üst 3.5_Üst": 3.96,
        "Karşılıklı Gol_Var": 1.82,
        "Karşılıklı Gol_Yok": 1.63,
        "İlk Yarı Sonucu_1": 2.72,
        "İlk Yarı Sonucu_0": 1.87,
        "İlk Yarı Sonucu_2": 3.9,
        "İlk Yarı Alt/Üst 0.5_Alt": 2.33,
        "İlk Yarı Alt/Üst 0.5_Üst": 1.37,
        "İlk Yarı Alt/Üst 1.5_Alt": 1.2,
        "İlk Yarı Alt/Üst 1.5_Üst": 3.05,
        "İlk Yarı Karşılıklı Gol_Var": 5.07,
        "İkinci Yarı Karşılıklı Gol_Var": 3.84,
        "İkinci Yarı Karşılıklı Gol_Yok": 1.11,
        "Ev Sahibi Alt/Üst 0.5_Alt": 3.14,
        "Ev Sahibi Alt/Üst 0.5_Üst": 1.19,
        "Ev Sahibi Alt/Üst 1.5_Alt": 1.39,
        "Ev Sahibi Alt/Üst 1.5_Üst": 2.25,
        "Deplasman Alt/Üst 0.5_Alt": 2.33,
        "Deplasman Alt/Üst 0.5_Üst": 1.37,
        "Deplasman Alt/Üst 1.5_Alt": 1.18,
        "Deplasman Alt/Üst 1.5_Üst": 3.16,
        "Ev Sahibi İlk Yarı Altı/Üstü 0.5_Alt": 1.54,
        "Ev Sahibi İlk Yarı Altı/Üstü 0.5_Üst": 1.94,
        "Deplasman İlk Yarı Altı/Üstü 0.5_Alt": 1.34,
        "Deplasman İlk Yarı Altı/Üstü 0.5_Üst": 2.41,
        "Her İki Yarıda da Alt 1.5_Evet": 1.89,
        "Her İki Yarıda da Alt 1.5_Hayır": 1.58,
        "Her İki Yarıda da Üst 1.5_Evet": 7.41,
        "Hangi Yarıda Daha Fazla Gol Olur_1.": 3.03,
        "Hangi Yarıda Daha Fazla Gol Olur_Eşit": 2.98,
        "Hangi Yarıda Daha Fazla Gol Olur_2.": 2.02,
        "Toplam Gol_0-1 gol": 2.56,
        "Toplam Gol_2-3 gol": 1.79,
        "Toplam Gol_4-5 gol": 4.61,
        "Toplam Gol_6+ gol": 24.85,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_1 ve Alt": 4.03,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_0 ve Alt": 2.31,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_2 ve Alt": 5.34,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_1 ve Üst": 7.38,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_0 ve Üst": 8.32,
        "İlk Yarı Sonucu ve Altı/Üstü 1.5_2 ve Üst": 12.45
    }
}

print(generate_story(match))
