import json
import rule_engine

match_data = {
    "lig": "Rusya Premier Lig",
    "ev_sahibi": "Rodina Moscow",
    "deplasman": "FK Rostov",
    "oranlar": {
        "Maç Sonucu_1": 2.78,
        "Maç Sonucu_0": 2.97,
        "Maç Sonucu_2": 2.16,
        "Handikaplı Maç Sonucu 0:1_1": 6.09,
        "Handikaplı Maç Sonucu 0:1_0": 4.24,
        "Handikaplı Maç Sonucu 0:1_2": 1.22,
        "Handikaplı Maç Sonucu 1:0_1": 1.4,
        "Handikaplı Maç Sonucu 1:0_0": 3.72,
        "Handikaplı Maç Sonucu 1:0_2": 4.27,
        "-_0": 6.07,
        "-_2": 10.45,
        "Maç Sonucu ve Alt/Üst 1.5_1 ve Alt": 9.14,
        "Maç Sonucu ve Alt/Üst 1.5_0 ve Alt": 9.23,
        "Maç Sonucu ve Alt/Üst 1.5_2 ve Alt": 7.82,
        "Maç Sonucu ve Alt/Üst 1.5_1 ve Üst": 3.79,
        "Maç Sonucu ve Alt/Üst 1.5_0 ve Üst": 4.1,
        "Maç Sonucu ve Alt/Üst 1.5_2 ve Üst": 2.84,
        "Maç Sonucu ve Alt/Üst 2.5_1 ve Alt": 5.8,
        "Maç Sonucu ve Alt/Üst 2.5_0 ve Alt": 3.67,
        "Maç Sonucu ve Alt/Üst 2.5_2 ve Alt": 4.69,
        "Maç Sonucu ve Alt/Üst 2.5_1 ve Üst": 4.96,
        "Maç Sonucu ve Alt/Üst 2.5_0 ve Üst": 12.6,
        "Maç Sonucu ve Alt/Üst 2.5_2 ve Üst": 3.74,
        "Maç Sonucu ve Alt/Üst 3.5_1 ve Alt": 3.55,
        "Maç Sonucu ve Alt/Üst 3.5_0 ve Alt": 3.67,
        "Maç Sonucu ve Alt/Üst 3.5_2 ve Alt": 2.86,
        "Maç Sonucu ve Alt/Üst 3.5_1 ve Üst": 10.9,
        "Maç Sonucu ve Alt/Üst 3.5_0 ve Üst": 12.6,
        "Maç Sonucu ve Alt/Üst 3.5_2 ve Üst": 7.7,
        "Maç Sonucu ve Alt/Üst 4.5_1 ve Alt": 3.1,
        "Maç Sonucu ve Alt/Üst 4.5_0 ve Alt": 2.96,
        "Maç Sonucu ve Alt/Üst 4.5_2 ve Alt": 2.44,
        "Maç Sonucu ve Alt/Üst 4.5_1 ve Üst": 19.55,
        "Maç Sonucu ve Alt/Üst 4.5_0 ve Üst": 35.5,
        "Maç Sonucu ve Alt/Üst 4.5_2 ve Üst": 14.05,
        "Ev Sahibi Her İki Yarıyı Kazanır_Evet": 10.85,
        "Deplasman Her İki Yarıyı Kazanır_Evet": 7.69,
        "1. Yarı / Maç Sonucu_1/1": 4.68,
        "1. Yarı / Maç Sonucu_1/0": 13.8,
        "1. Yarı / Maç Sonucu_1/2": 29.5,
        "1. Yarı / Maç Sonucu_0/1": 6.43,
        "1. Yarı / Maç Sonucu_0/0": 4.37,
        "1. Yarı / Maç Sonucu_0/2": 5.31,
        "1. Yarı / Maç Sonucu_2/1": 34.5,
        "1. Yarı / Maç Sonucu_2/0": 13.45,
        "1. Yarı / Maç Sonucu_2/2": 3.47,
        "Çifte Şans_1 ve 0": 1.43,
        "Çifte Şans_1 ve 2": 1.22,
        "Çifte Şans_0 ve 2": 1.25,
        "Hangi Takım Kaç Farkla Kazanır?_Ev 3+": 15.5,
        "Hangi Takım Kaç Farkla Kazanır?_Ev 2": 7.35,
        "Hangi Takım Kaç Farkla Kazanır?_Ev 1": 3.61,
        "Hangi Takım Kaç Farkla Kazanır?_Dep 1": 3.13,
        "Hangi Takım Kaç Farkla Kazanır?_Dep 2": 5.45,
        "Hangi Takım Kaç Farkla Kazanır?_Dep 3+": 9.27,
        "Hangi Takım Kaç Farkla Kazanır?_0": 2.37,
        "1. Yarı Sonucu_1": 3.45,
        "1. Yarı Sonucu_0": 1.94,
        "1. Yarı Sonucu_2": 2.81,
        "2. Yarı Sonucu_1": 3.04,
        "2. Yarı Sonucu_0": 2.29,
        "2. Yarı Sonucu_2": 2.52,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_1 ve Var": 24.85,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_1 ve Yok": 3.84,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_0 ve Var": 7.55,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_0 ve Yok": 2.48,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_2 ve Var": 20.5,
        "1. Yarı Sonucu ve İlk Yarı Karşılıklı Gol_2 ve Yok": 3.12,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_1 ve Alt": 5.02,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_0 ve Alt": 2.49,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_2 ve Alt": 4.29,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_1 ve Üst": 9.81,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_0 ve Üst": 7.59,
        "1. Yarı Sonucu ve Altı/Üstü 1.5_2 ve Üst": 7.3,
        "1. Yarı Karşılıklı Gol_Var": 4.53,
        "1. Yarı Karşılıklı Gol_Yok": 1.07,
        "1. Yarı Çifte Şans_1 ve 0": 1.24,
        "1. Yarı Çifte Şans_1 ve 2": 1.54,
        "1. Yarı Çifte Şans_0 ve 2": 1.15,
        "1. Yarı Tek/Çift_Tek": 1.95,
        "1. Yarı Tek/Çift_Çift": 1.54,
        "1. Yarı Skoru_0:0": 2.49,
        "Karşılıklı Gol_Var": 1.67,
        "Karşılıklı Gol_Yok": 1.78,
        "Maç Sonucu ve Karşılıklı Gol_1 ve Var": 5.96,
        "Maç Sonucu ve Karşılıklı Gol_1 ve Yok": 4.86,
        "Maç Sonucu ve Karşılıklı Gol_0 ve Var": 4.11,
        "Maç Sonucu ve Karşılıklı Gol_0 ve Yok": 9.23,
        "Maç Sonucu ve Karşılıklı Gol_2 ve Var": 4.73,
        "Maç Sonucu ve Karşılıklı Gol_2 ve Yok": 3.71,
        "Toplam Gol_0-1 gol": 2.9,
        "Toplam Gol_2-3 gol": 1.79,
        "Toplam Gol_4-5 gol": 4.02,
        "Toplam Gol_6+ gol": 18.45,
        "İlk Golü Hangi Takım Atar_1": 2.05,
        "İlk Golü Hangi Takım Atar_Gol Olmaz": 9.5,
        "İlk Golü Hangi Takım Atar_2": 1.77,
        "Hangi Yarıda Daha Fazla Gol Olur_1.": 2.99,
        "Hangi Yarıda Daha Fazla Gol Olur_Eşit": 3.11,
        "Hangi Yarıda Daha Fazla Gol Olur_2.": 1.99,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_1.": 3.5,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_Eşit": 2.05,
        "Ev Sahibi Hangi Yarıda Daha Fazla Gol Atar_2.": 2.59,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_1.": 3.27,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_Eşit": 2.24,
        "Deplasman Hangi Yarıda Daha Fazla Gol Atar_2.": 2.45,
        "Tek / Çift_Tek": 1.79,
        "Tek / Çift_Çift": 1.66,
        "2. Yarı Karşılıklı Gol_Var": 3.43,
        "2. Yarı Karşılıklı Gol_Yok": 1.15,
        "Ev Sahibi Her İki Yarıda da Gol Atar_Evet": 4.44,
        "Ev Sahibi Her İki Yarıda da Gol Atar_Hayır": 1.07,
        "Deplasman Her İki Yarıda da Gol Atar_Evet": 3.6,
        "Deplasman Her İki Yarıda da Gol Atar_Hayır": 1.14,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Hayır / Hayır": 1.38,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Evet / Hayır": 5.88,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Evet / Evet": 18.6,
        "1. Yarı ve 2. Yarıda Karşılıklı Gol Olur_Hayır / Evet": 4.06,
        "Alt/Üst 0.5_Alt": 8.43,
        "Alt/Üst 1.5_Alt": 2.96,
        "Alt/Üst 1.5_Üst": 1.22,
        "Alt/Üst 2.5_Alt": 1.58,
        "Alt/Üst 2.5_Üst": 1.89,
        "Alt/Üst 3.5_Alt": 1.15,
        "Alt/Üst 3.5_Üst": 3.38,
        "-_Üst": 7.45,
        "Ev Sahibi Alt/Üst 0.5_Alt": 2.7,
        "Ev Sahibi Alt/Üst 0.5_Üst": 1.27,
        "Ev Sahibi Alt/Üst 1.5_Alt": 1.28,
        "Ev Sahibi Alt/Üst 1.5_Üst": 2.64,
        "Deplasman Alt/Üst 0.5_Alt": 3.23,
        "Deplasman Alt/Üst 0.5_Üst": 1.17,
        "Deplasman Alt/Üst 1.5_Alt": 1.42,
        "Deplasman Alt/Üst 1.5_Üst": 2.2,
        "Her İki Yarıda da Alt 1.5_Evet": 2.08,
        "Her İki Yarıda da Alt 1.5_Hayır": 1.47,
        "Her İki Yarıda da Üst 1.5_Evet": 6.26,
        "1. Yarı Alt/Üst 0.5_Alt": 2.52,
        "1. Yarı Alt/Üst 0.5_Üst": 1.31,
        "1. Yarı Alt/Üst 1.5_Alt": 1.25,
        "1. Yarı Alt/Üst 1.5_Üst": 2.78,
        "Ev Sahibi 1. Yarı Altı/Üstü 0.5_Alt": 1.44,
        "Ev Sahibi 1. Yarı Altı/Üstü 0.5_Üst": 2.16,
        "Deplasman 1. Yarı Altı/Üstü 0.5_Alt": 1.56,
        "Deplasman 1. Yarı Altı/Üstü 0.5_Üst": 1.92,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Alt ve Var": 6.0,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Üst ve Var": 2.22,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Alt ve Yok": 2.07,
        "Altı/Üstü 2.5 ve Karşılıklı Gol_Üst ve Yok": 10.85,
    }
}

rule_engine.CURRENT_MATCH = match_data
print("Testing ALL rules manually:")
for rule_class in rule_engine.get_all_rules():
    triggered, msg = rule_class.evaluate(match_data['oranlar'])
    if triggered:
        print(f"[ACTIVE] {rule_class.code}: {rule_class.name}")
    else:
        pass
